### ISSUE TITLE
A data de nascimento do portador do cartão é inválida

### ISSUE THREAD

**Issue by michaeloc** [zoiverd/moip-net#2]
Estou tentando colocar a data de nascimento do portador do cartão mas recebo um erro informando que a data é inválida, mesmo seguindo o padrão "yyyy-MM-dd". Esse problema somente ocorre na criação do pagamento.

**Comment by zoiverd** [comment]
Oi Michael,

Realmente eles alteraram alguma coisa lá, pq eu fiz os testes via Postman e também recebo este mesmo retorno.
Estou fazendo este post:

URI: https://sandbox.moip.com.br/v2/customers/{{customer_id}}/fundinginstruments
{
  "method": "CREDIT_CARD",
  "creditCard": {
    "number": "5555666677778884",
    "expirationMonth": 5,
    "expirationYear": 20,
    "cvc": 123,
    "brand": "VISA",
    "holder": {
      "fullname": "Jose Portador da Silva",
      "birthDate": "1998-11-17",
      "phone": {
        "countryCode": 55,
        "areaCode": 11,
        "number": 67888888
      },
      "taxDocument": {
        "type": "CPF",
        "number": "65374721054"
      }
    }
  }
}

E está correto segundo a documentação, mas volta este erro agora.
Você consegue verificar com o moip se houve alguma mudança nas validações deste campo?

**Comment by zoiverd** [comment]
Obrigado,
Merge feito, pacote atualizado no nuget para versão 0.0.7.
