### ISSUE TITLE
Criptografia do cartão de crédito

### ISSUE THREAD

**Issue by rrispoli** [zoiverd/moip-net#4]
Há planos para inclusão da criptografia do cartão de crédito, a fim de evitar que os dados sensíveis sejam diretamente enviados?

**Comment by zoiverd** [comment]
Oi RRISPOLI,

Tecnicamente os dados são enviados criptografados por se tratar de uma conexão SSL com a API.

E sendo o caso de criptografar o correto, pra mim, seria criptografar no browser do usuário via javascript (que é a ponta mais frágil).

Caso você opte por criptografar no browser usando a biblioteca js deles, você pode mandar o hash que já está implementado (embora não tenha sido testado ainda).

Documentação moip: http://dev.moip.com.br/docs/#capturando-os-dados-do-carto-de-crdito

**Comment by rrispoli** [comment]
Olá @zoiverd, entendi, perguntei mesmo pois estou iniciando a implementação aqui e encontrei essa instrução de gerar o hash pelo javascript, mas faz sentido o que você falou. No meu caso nem existirá o browser, já que é um aplicativo Xamarin se comunicando com minha aplicação ASP.NET.

Obrigado!

**Comment by zoiverd** [comment]
Ok! Você pode então criptografar fora da biblioteca e enviar o hash apenas 👍

**Comment by matmiranda** [comment]
@zoiverd essa biblioteca parou ?
